package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            password("PASSWORD", "credentialsJSON:51b652cf-c42d-49ba-b32b-d7e373105bd3", label = "Password", description = "Centyllion JKS Password", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }
}
